def song(age_adjective,name,place,animal,animal_sound,second_animal,second_animal_sound,third_animal,third_animal_sound):
    print()
    print()
    print(f"{age_adjective} {name} had a {place}, E I E I O,")
    print(f"And on that {place}, he had a {animal}, E I E I O.")
    print(f"With a {animal_sound} {animal_sound} here and a {animal_sound} {animal_sound} there,")
    print(f"Here a {animal_sound}, there a {animal_sound}, everywhere a {animal_sound} {animal_sound}.")
    print(f"Old {name} had a {place}, E I E I O.")
    print()
    print(f"{age_adjective} {name} had a {place}, E I E I O,")
    print(f"And on that {place}, he had a {second_animal}, E I E I O.")
    print(f"With a {second_animal_sound} {second_animal_sound} here and a {second_animal_sound} {second_animal_sound} there,")
    print(f"Here a {second_animal_sound}, there a {second_animal_sound}, everywhere a {second_animal_sound} {second_animal_sound}.")
    print(f"Old {name} had a {place}, E I E I O.")
    print()
    print(f"{age_adjective} {name} had a {place}, E I E I O,")
    print(f"And on that {place}, he had a {third_animal}, E I E I O.")
    print(f"With a {third_animal_sound} {third_animal_sound} here and a {third_animal_sound} {third_animal_sound} there,")
    print(f"Here a {third_animal_sound}, there a {third_animal_sound}, everywhere a {third_animal_sound} {third_animal_sound}.")
    print(f"Old {name} had a {place}, E I E I O.")
    
age_adjective = input("Give me a age-adjective: ")
name = input("Give me a name: ")
place = input("Give me a place: ")
animal = input("Give me an animal: ")
animal_sound = input("Give me an animal sound: ")
second_animal = input("Give me a second animal: ")
second_animal_sound = input("Give me a second animal sound: ")
third_animal = input("Give me a third animal: ")
third_animal_sound = input("Give me a third animal sound: ")

song(age_adjective,name,place,animal,animal_sound,second_animal,second_animal_sound,third_animal,third_animal_sound)